name: Build servers with CMake
# build_servers_cmake.yml


on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Create build directory
        run: mkdir cbuild

      - name: Create Unix Makefiles
        run: |
          cd cbuild
          cmake -G "Unix Makefiles" ..

      - name: Command - make
        run: |
          cd cbuild
          make
